steps:
  # Build Docker Image
  - name: "Build Docker Image"
    image: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/probable-drive-451406-r7/frontend:$SHORT_SHA",
        ".",
      ]
  # Push Docker Image to Google Container Registry (GCR)
  - name: "Push Docker Image"
    image: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/probable-drive-451406-r7/frontend:$SHORT_SHA"]
  # Deploy to Cloud Run
  - name: "Deploy to Cloud Run"
    image: "gcr.io/google-cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "your-frontend-service" # ชื่อ Cloud Run Service ของ Frontend
      - "--image"
      - "gcr.io/probable-drive-451406-r7/frontend:$SHORT_SHA"
      - "--region"
      - "asia-southeast1" # เปลี่ยนเป็น Region ที่คุณต้องการ
      - "--platform"
      - "managed"
      - "--port"
      - "80" # Nginx listen บน Port 80
      - "--allow-unauthenticated"
      - "--update-env-vars"
      - "VITE_API_URL=https://strapi-cloudrun-service-432784522460.asia-southeast1.run.app,VITE_SOME_KEY=ABC123" # ส่ง Environment Variables

substitutions:
  _SHORT_SHA: $(short_sha)
